"""initial schema

Revision ID: 33f25a893516
Revises: 
Create Date: 2026-09-16 11:43:40.086423+03:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '33f25a893516'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('SPORT', 'TECH', 'ART', 'SPECIAL_INTEREST', name='club_category', create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criteria',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('SPORT', 'TECH', 'ART', 'SPECIAL_INTEREST', name='club_category', create_constraint=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rules_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('semester', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sso_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('GUEST', 'CLUB_LEADER', 'MODERATOR', name='user_role', create_constraint=True), nullable=False),
    sa.Column('can_sudo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sso_id')
    )
    op.create_table('access_violations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archive_batches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('performed_by_role', sa.String(length=32), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_leaders',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('club_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'user_id', name='uq_club_leaders_club_user')
    )
    op.create_table('criteria_rules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('criteria_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['criteria_id'], ['criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['rules_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sudo_actions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('performed_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('club_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('criteria_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rules_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('activity_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ON_MODERATION', 'CHANGES_REQUIRED', 'APPROVED', 'DISPUTED', 'COMPLETED', 'CLOSED', 'ARCHIVED', name='report_status', create_constraint=True), nullable=False),
    sa.Column('calculated_points', sa.Integer(), nullable=True),
    sa.Column('final_points', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_batch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('moderated_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderation_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['archive_batch_id'], ['archive_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criteria_id'], ['criteria.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['moderated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rules_version_id'], ['rules_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('report_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'])
    op.create_index('ix_audit_logs_performed_at', 'audit_logs', ['performed_at'])
    op.create_index('ix_reports_club_status', 'reports', ['club_id', 'status'])
    op.create_index('ix_reports_status', 'reports', ['status'])
    op.create_index('ix_report_links_url', 'report_links', ['url'])
    op.create_index('ix_report_links_report_id', 'report_links', ['report_id'])

    # Append-only enforcement for audit_logs (even for table owner).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_audit_logs_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_logs is append-only (attempted %)', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_logs_append_only
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION prevent_audit_logs_mutation();
        """
    )
    op.execute("REVOKE UPDATE, DELETE ON audit_logs FROM PUBLIC;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_append_only ON audit_logs;")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_logs_mutation();")
    op.drop_index('ix_report_links_report_id', table_name='report_links')
    op.drop_index('ix_report_links_url', table_name='report_links')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_club_status', table_name='reports')
    op.drop_index('ix_audit_logs_performed_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('report_links')
    op.drop_table('reports')
    op.drop_table('sudo_actions')
    op.drop_table('criteria_rules')
    op.drop_table('club_leaders')
    op.drop_table('audit_logs')
    op.drop_table('archive_batches')
    op.drop_table('access_violations')
    op.drop_table('users')
    op.drop_table('rules_versions')
    op.drop_table('criteria')
    op.drop_table('clubs')
    # ### end Alembic commands ###
